//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteAhorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí, abandonar.
        /// </summary>
        public static string Abandonar_Confirmar {
            get {
                return ResourceManager.GetString("Abandonar_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 puntos.
        /// </summary>
        public static string Abandonar_Puntos {
            get {
                return ResourceManager.GetString("Abandonar_Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si abandonas se te restarán.
        /// </summary>
        public static string Abandonar_TextoAntes {
            get {
                return ResourceManager.GetString("Abandonar_TextoAntes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de tu puntaje global y se cancelará la partida para ambos jugadores..
        /// </summary>
        public static string Abandonar_TextoDespues {
            get {
                return ResourceManager.GetString("Abandonar_TextoDespues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Abandonar la partida?.
        /// </summary>
        public static string Abandonar_Titulo {
            get {
                return ResourceManager.GetString("Abandonar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a la partida.
        /// </summary>
        public static string Abandonar_Volver {
            get {
                return ResourceManager.GetString("Abandonar_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entra a tu cuenta para guardar tu progreso, o crea una cuenta gratis para empezar a jugar..
        /// </summary>
        public static string Bienvenida_Descripcion {
            get {
                return ResourceManager.GetString("Bienvenida_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 intentos.
        /// </summary>
        public static string Bienvenida_Intentos {
            get {
                return ResourceManager.GetString("Bienvenida_Intentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_O__A__.
        /// </summary>
        public static string Bienvenida_PalabraDecorativa {
            get {
                return ResourceManager.GetString("Bienvenida_PalabraDecorativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adivina la palabra letra por letra antes de quedarte sin intentos..
        /// </summary>
        public static string Bienvenida_Subtitulo {
            get {
                return ResourceManager.GetString("Bienvenida_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡El Ahorcado!.
        /// </summary>
        public static string Bienvenida_Titulo {
            get {
                return ResourceManager.GetString("Bienvenida_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        public static string CambiarContrasena_ContrasenaActual {
            get {
                return ResourceManager.GetString("CambiarContrasena_ContrasenaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta..
        /// </summary>
        public static string CambiarContrasena_ErrorActualIncorrecta {
            get {
                return ResourceManager.GetString("CambiarContrasena_ErrorActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu contraseña actual..
        /// </summary>
        public static string CambiarContrasena_ErrorActualVacia {
            get {
                return ResourceManager.GetString("CambiarContrasena_ErrorActualVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu contraseña se cambió correctamente..
        /// </summary>
        public static string CambiarContrasena_ExitoMensaje {
            get {
                return ResourceManager.GetString("CambiarContrasena_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actualizada.
        /// </summary>
        public static string CambiarContrasena_ExitoTitulo {
            get {
                return ResourceManager.GetString("CambiarContrasena_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string CambiarContrasena_NuevaContrasena {
            get {
                return ResourceManager.GetString("CambiarContrasena_NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por seguridad, ingresa tu contraseña actual para continuar..
        /// </summary>
        public static string CambiarContrasena_Paso1 {
            get {
                return ResourceManager.GetString("CambiarContrasena_Paso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu nueva contraseña..
        /// </summary>
        public static string CambiarContrasena_Paso2 {
            get {
                return ResourceManager.GetString("CambiarContrasena_Paso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string CambiarContrasena_Titulo {
            get {
                return ResourceManager.GetString("CambiarContrasena_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Comun_Aceptar {
            get {
                return ResourceManager.GetString("Comun_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es obligatorio..
        /// </summary>
        public static string Comun_CampoObligatorio {
            get {
                return ResourceManager.GetString("Comun_CampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Comun_Cancelar {
            get {
                return ResourceManager.GetString("Comun_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string Comun_Categoria {
            get {
                return ResourceManager.GetString("Comun_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💬  Chat.
        /// </summary>
        public static string Comun_Chat {
            get {
                return ResourceManager.GetString("Comun_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Comun_Continuar {
            get {
                return ResourceManager.GetString("Comun_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Comun_Contrasena {
            get {
                return ResourceManager.GetString("Comun_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string Comun_CorreoElectronico {
            get {
                return ResourceManager.GetString("Comun_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Comun_Error {
            get {
                return ResourceManager.GetString("Comun_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un correo electrónico válido..
        /// </summary>
        public static string comun_ErrorCorreoInvalido {
            get {
                return ResourceManager.GetString("comun_ErrorCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pts.
        /// </summary>
        public static string Comun_FormatoPuntos {
            get {
                return ResourceManager.GetString("Comun_FormatoPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} pts.
        /// </summary>
        public static string Comun_FormatoPuntosPositivos {
            get {
                return ResourceManager.GetString("Comun_FormatoPuntosPositivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Comun_Guardar {
            get {
                return ResourceManager.GetString("Comun_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string Comun_IniciarSesion {
            get {
                return ResourceManager.GetString("Comun_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión.
        /// </summary>
        public static string Comun_IniciaSesion {
            get {
                return ResourceManager.GetString("Comun_IniciaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al lobby.
        /// </summary>
        public static string Comun_IrAlLobby {
            get {
                return ResourceManager.GetString("Comun_IrAlLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar de nuevo.
        /// </summary>
        public static string Comun_JugarDeNuevo {
            get {
                return ResourceManager.GetString("Comun_JugarDeNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabra.
        /// </summary>
        public static string Comun_Palabra {
            get {
                return ResourceManager.GetString("Comun_Palabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntaje global.
        /// </summary>
        public static string Comun_PuntajeGlobal {
            get {
                return ResourceManager.GetString("Comun_PuntajeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos obtenidos.
        /// </summary>
        public static string Comun_PuntosObtenidos {
            get {
                return ResourceManager.GetString("Comun_PuntosObtenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar cuenta.
        /// </summary>
        public static string Comun_RegistrarCuenta {
            get {
                return ResourceManager.GetString("Comun_RegistrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        public static string Comun_Registrate {
            get {
                return ResourceManager.GetString("Comun_Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rival.
        /// </summary>
        public static string Comun_Rival {
            get {
                return ResourceManager.GetString("Comun_Rival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string Comun_Salir {
            get {
                return ResourceManager.GetString("Comun_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⇐ Volver.
        /// </summary>
        public static string Comun_Volver {
            get {
                return ResourceManager.GetString("Comun_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres jugar otra partida con .
        /// </summary>
        public static string DialogoResultado_PreguntaPrefijo {
            get {
                return ResourceManager.GetString("DialogoResultado_PreguntaPrefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string DialogoResultado_PreguntaSufijo {
            get {
                return ResourceManager.GetString("DialogoResultado_PreguntaSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string EditarPerfil_CambiarContrasena {
            get {
                return ResourceManager.GetString("EditarPerfil_CambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITANDO.
        /// </summary>
        public static string EditarPerfil_Editando {
            get {
                return ResourceManager.GetString("EditarPerfil_Editando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener 8+ caracteres, mayúscula, minúscula y número..
        /// </summary>
        public static string EditarPerfil_ErrorContrasenaRequisitos {
            get {
                return ResourceManager.GetString("EditarPerfil_ErrorContrasenaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus cambios se guardaron correctamente..
        /// </summary>
        public static string EditarPerfil_ExitoMensaje {
            get {
                return ResourceManager.GetString("EditarPerfil_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil actualizado.
        /// </summary>
        public static string EditarPerfil_ExitoTitulo {
            get {
                return ResourceManager.GetString("EditarPerfil_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string EditarPerfil_GuardarCambios {
            get {
                return ResourceManager.GetString("EditarPerfil_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña (opcional).
        /// </summary>
        public static string EditarPerfil_NuevaContrasena {
            get {
                return ResourceManager.GetString("EditarPerfil_NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualiza tus datos (el correo no puede cambiarse).
        /// </summary>
        public static string EditarPerfil_Subtitulo {
            get {
                return ResourceManager.GetString("EditarPerfil_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        public static string EditarPerfil_Titulo {
            get {
                return ResourceManager.GetString("EditarPerfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Editar perfil.
        /// </summary>
        public static string EditarPerfil_TituloVentana {
            get {
                return ResourceManager.GetString("EditarPerfil_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar ⇒.
        /// </summary>
        public static string ElegirCategoria_Continuar {
            get {
                return ResourceManager.GetString("ElegirCategoria_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una categoría para continuar..
        /// </summary>
        public static string ElegirCategoria_ErrorMensaje {
            get {
                return ResourceManager.GetString("ElegirCategoria_ErrorMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 1 de 2 · Elige una categoría.
        /// </summary>
        public static string ElegirCategoria_Paso {
            get {
                return ResourceManager.GetString("ElegirCategoria_Paso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Elegir categoría.
        /// </summary>
        public static string ElegirCategoria_TituloVentana {
            get {
                return ResourceManager.GetString("ElegirCategoria_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría: {0}.
        /// </summary>
        public static string ElegirPalabra_CategoriaConNombre {
            get {
                return ResourceManager.GetString("ElegirPalabra_CategoriaConNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar palabra.
        /// </summary>
        public static string ElegirPalabra_Confirmar {
            get {
                return ResourceManager.GetString("ElegirPalabra_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una palabra para continuar..
        /// </summary>
        public static string ElegirPalabra_ErrorMensaje {
            get {
                return ResourceManager.GetString("ElegirPalabra_ErrorMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  letras.
        /// </summary>
        public static string ElegirPalabra_LetrasSufijo {
            get {
                return ResourceManager.GetString("ElegirPalabra_LetrasSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 2 de 2 · Elige una palabra.
        /// </summary>
        public static string ElegirPalabra_Paso {
            get {
                return ResourceManager.GetString("ElegirPalabra_Paso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Elegir palabra.
        /// </summary>
        public static string ElegirPalabra_TituloVentana {
            get {
                return ResourceManager.GetString("ElegirPalabra_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}.
        /// </summary>
        public static string EsperandoPalabra_CreadorBoton {
            get {
                return ResourceManager.GetString("EsperandoPalabra_CreadorBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} está eligiendo la palabra....
        /// </summary>
        public static string EsperandoPalabra_Eligiendo {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Eligiendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando termine, comenzarás a adivinar. Te avisaremos en cuanto la palabra esté lista..
        /// </summary>
        public static string EsperandoPalabra_Instruccion {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Instruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu rival está eligiendo la palabra que tendrás que adivinar.
        /// </summary>
        public static string EsperandoPalabra_Subtitulo {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Te uniste a la partida!.
        /// </summary>
        public static string EsperandoPalabra_TeUniste {
            get {
                return ResourceManager.GetString("EsperandoPalabra_TeUniste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Esperando palabra.
        /// </summary>
        public static string EsperandoPalabra_TituloVentana {
            get {
                return ResourceManager.GetString("EsperandoPalabra_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú.
        /// </summary>
        public static string EsperandoPalabra_TuBoton {
            get {
                return ResourceManager.GetString("EsperandoPalabra_TuBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vs.
        /// </summary>
        public static string EsperandoPalabra_Vs {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Vs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar partida.
        /// </summary>
        public static string EsperandoRival_CancelarPartida {
            get {
                return ResourceManager.GetString("EsperandoRival_CancelarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que deseas cancelar la partida?.
        /// </summary>
        public static string EsperandoRival_ConfirmarCancelar {
            get {
                return ResourceManager.GetString("EsperandoRival_ConfirmarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu partida aparece en la lista del lobby. En cuanto alguien se una, podrás elegir la palabra que tendrá que adivinar..
        /// </summary>
        public static string EsperandoRival_Descripcion {
            get {
                return ResourceManager.GetString("EsperandoRival_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu partida está lista.
        /// </summary>
        public static string EsperandoRival_Encabezado {
            get {
                return ResourceManager.GetString("EsperandoRival_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ···  Esperando....
        /// </summary>
        public static string EsperandoRival_Esperando {
            get {
                return ResourceManager.GetString("EsperandoRival_Esperando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartiendo en el lobby para que alguien se una.
        /// </summary>
        public static string EsperandoRival_Subtitulo {
            get {
                return ResourceManager.GetString("EsperandoRival_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIEMPO EN ESPERA.
        /// </summary>
        public static string EsperandoRival_TiempoEnEspera {
            get {
                return ResourceManager.GetString("EsperandoRival_TiempoEnEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando a un rival....
        /// </summary>
        public static string EsperandoRival_Titulo {
            get {
                return ResourceManager.GetString("EsperandoRival_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Esperando oponente.
        /// </summary>
        public static string EsperandoRival_TituloVentana {
            get {
                return ResourceManager.GetString("EsperandoRival_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú.
        /// </summary>
        public static string EsperandoRival_Tu {
            get {
                return ResourceManager.GetString("EsperandoRival_Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganaste +10 puntos por esta partida.
        /// </summary>
        public static string GanadorAdivinador_Subtitulo {
            get {
                return ResourceManager.GetString("GanadorAdivinador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Adivinaste la palabra!.
        /// </summary>
        public static string GanadorAdivinador_Titulo {
            get {
                return ResourceManager.GetString("GanadorAdivinador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganaste +5 puntos por crear la partida.
        /// </summary>
        public static string GanadorCreador_Subtitulo {
            get {
                return ResourceManager.GetString("GanadorCreador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu rival no pudo adivinar.
        /// </summary>
        public static string GanadorCreador_Titulo {
            get {
                return ResourceManager.GetString("GanadorCreador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas ganadas ({0}).
        /// </summary>
        public static string Historial_BtnGanadas {
            get {
                return ResourceManager.GetString("Historial_BtnGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalizaciones ({0}).
        /// </summary>
        public static string Historial_BtnPenalizaciones {
            get {
                return ResourceManager.GetString("Historial_BtnPenalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rival no adivinó ({0}).
        /// </summary>
        public static string Historial_BtnRival {
            get {
                return ResourceManager.GetString("Historial_BtnRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA.
        /// </summary>
        public static string Historial_ColFecha {
            get {
                return ResourceManager.GetString("Historial_ColFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALABRA ADIVINADA.
        /// </summary>
        public static string Historial_ColPalabraGanadas {
            get {
                return ResourceManager.GetString("Historial_ColPalabraGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALABRA EN JUEGO.
        /// </summary>
        public static string Historial_ColPalabraPenal {
            get {
                return ResourceManager.GetString("Historial_ColPalabraPenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALABRA ELEGIDA.
        /// </summary>
        public static string Historial_ColPalabraRival {
            get {
                return ResourceManager.GetString("Historial_ColPalabraRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNTOS.
        /// </summary>
        public static string Historial_ColPuntos {
            get {
                return ResourceManager.GetString("Historial_ColPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIVAL VENCIDO.
        /// </summary>
        public static string Historial_ColRivalGanadas {
            get {
                return ResourceManager.GetString("Historial_ColRivalGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIDA ABANDONADA.
        /// </summary>
        public static string Historial_ColRivalPenal {
            get {
                return ResourceManager.GetString("Historial_ColRivalPenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIVAL QUE FALLÓ.
        /// </summary>
        public static string Historial_ColRivalRival {
            get {
                return ResourceManager.GetString("Historial_ColRivalRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GANADAS.
        /// </summary>
        public static string Historial_Ganadas {
            get {
                return ResourceManager.GetString("Historial_Ganadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENALIZACIONES.
        /// </summary>
        public static string Historial_Penalizaciones {
            get {
                return ResourceManager.GetString("Historial_Penalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pts.
        /// </summary>
        public static string Historial_PtsSufijo {
            get {
                return ResourceManager.GetString("Historial_PtsSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNTAJE GLOBAL.
        /// </summary>
        public static string Historial_PuntajeGlobalEtiqueta {
            get {
                return ResourceManager.GetString("Historial_PuntajeGlobalEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} pts.
        /// </summary>
        public static string Historial_PuntosGanados {
            get {
                return ResourceManager.GetString("Historial_PuntosGanados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to –{0} pts.
        /// </summary>
        public static string Historial_PuntosPerdidos {
            get {
                return ResourceManager.GetString("Historial_PuntosPerdidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIVAL NO ADIVINÓ.
        /// </summary>
        public static string Historial_RivalNoAdivino {
            get {
                return ResourceManager.GetString("Historial_RivalNoAdivino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay registros en esta categoría..
        /// </summary>
        public static string Historial_SinRegistros {
            get {
                return ResourceManager.GetString("Historial_SinRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu progreso, partida por partida.
        /// </summary>
        public static string Historial_Subtitulo {
            get {
                return ResourceManager.GetString("Historial_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de puntajes.
        /// </summary>
        public static string Historial_Titulo {
            get {
                return ResourceManager.GetString("Historial_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Historial.
        /// </summary>
        public static string Historial_TituloVentana {
            get {
                return ResourceManager.GetString("Historial_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña que ingresaste es incorrecta..
        /// </summary>
        public static string IniciarSesion_ErrorContrasena {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu contraseña..
        /// </summary>
        public static string IniciarSesion_ErrorContrasenaVacia {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasenaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo electrónico no existe..
        /// </summary>
        public static string IniciarSesion_ErrorCorreo {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu correo electrónico..
        /// </summary>
        public static string IniciarSesion_ErrorCorreoVacio {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes cuenta?.
        /// </summary>
        public static string IniciarSesion_NoTienesCuenta {
            get {
                return ResourceManager.GetString("IniciarSesion_NoTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido de vuelta.
        /// </summary>
        public static string IniciarSesion_Subtitulo {
            get {
                return ResourceManager.GetString("IniciarSesion_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandonar partida.
        /// </summary>
        public static string Juego_AbandonarPartida {
            get {
                return ResourceManager.GetString("Juego_AbandonarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORÍA.
        /// </summary>
        public static string Juego_CategoriaEtiqueta {
            get {
                return ResourceManager.GetString("Juego_CategoriaEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que deseas abandonar la partida? Perderás puntos..
        /// </summary>
        public static string Juego_ConfirmarAbandono {
            get {
                return ResourceManager.GetString("Juego_ConfirmarAbandono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPCIÓN.
        /// </summary>
        public static string Juego_DescripcionEtiqueta {
            get {
                return ResourceManager.GetString("Juego_DescripcionEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando que el creador elija la palabra....
        /// </summary>
        public static string Juego_EsperandoPalabra {
            get {
                return ResourceManager.GetString("Juego_EsperandoPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  intentos restantes.
        /// </summary>
        public static string Juego_IntentosRestantes {
            get {
                return ResourceManager.GetString("Juego_IntentosRestantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LETRAS INCORRECTAS:  .
        /// </summary>
        public static string Juego_LetrasIncorrectas {
            get {
                return ResourceManager.GetString("Juego_LetrasIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} abandonó la partida. Regresarás al lobby..
        /// </summary>
        public static string Juego_RivalAbandonoMensaje {
            get {
                return ResourceManager.GetString("Juego_RivalAbandonoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rival abandonó.
        /// </summary>
        public static string Juego_RivalAbandonoTitulo {
            get {
                return ResourceManager.GetString("Juego_RivalAbandonoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rival está adivinando.
        /// </summary>
        public static string Juego_RivalAdivinando {
            get {
                return ResourceManager.GetString("Juego_RivalAdivinando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Partida en curso.
        /// </summary>
        public static string Juego_TituloVentana {
            get {
                return ResourceManager.GetString("Juego_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú (adivinando).
        /// </summary>
        public static string Juego_TuAdivinando {
            get {
                return ResourceManager.GetString("Juego_TuAdivinando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú (creador).
        /// </summary>
        public static string Juego_TuCreador {
            get {
                return ResourceManager.GetString("Juego_TuCreador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU PALABRA:  .
        /// </summary>
        public static string Juego_TuPalabra {
            get {
                return ResourceManager.GetString("Juego_TuPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu rival.
        /// </summary>
        public static string Juego_TuRival {
            get {
                return ResourceManager.GetString("Juego_TuRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vs {0}.
        /// </summary>
        public static string Juego_VsRival {
            get {
                return ResourceManager.GetString("Juego_VsRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string Partidas_CerrarSesion {
            get {
                return ResourceManager.GetString("Partidas_CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREADA.
        /// </summary>
        public static string Partidas_ColCreada {
            get {
                return ResourceManager.GetString("Partidas_ColCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREADOR.
        /// </summary>
        public static string Partidas_ColCreador {
            get {
                return ResourceManager.GetString("Partidas_ColCreador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Partidas_ColIdioma {
            get {
                return ResourceManager.GetString("Partidas_ColIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGADORES.
        /// </summary>
        public static string Partidas_ColJugadores {
            get {
                return ResourceManager.GetString("Partidas_ColJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que deseas cerrar sesión?.
        /// </summary>
        public static string Partidas_ConfirmarCerrarMensaje {
            get {
                return ResourceManager.GetString("Partidas_ConfirmarCerrarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Crear partida.
        /// </summary>
        public static string Partidas_CrearPartida {
            get {
                return ResourceManager.GetString("Partidas_CrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partidas disponibles.
        /// </summary>
        public static string Partidas_DisponiblesSufijo {
            get {
                return ResourceManager.GetString("Partidas_DisponiblesSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · Cada partida es de 2 jugadores.
        /// </summary>
        public static string Partidas_DosJugadores {
            get {
                return ResourceManager.GetString("Partidas_DosJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexión con base de datos, inténtelo más tarde..
        /// </summary>
        public static string Partidas_ErrorConexion {
            get {
                return ResourceManager.GetString("Partidas_ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de puntajes.
        /// </summary>
        public static string Partidas_HistorialPuntajes {
            get {
                return ResourceManager.GetString("Partidas_HistorialPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Partidas_IdiomaPartidaEspanol {
            get {
                return ResourceManager.GetString("Partidas_IdiomaPartidaEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string Partidas_IdiomaPartidaIngles {
            get {
                return ResourceManager.GetString("Partidas_IdiomaPartidaIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta partida ya no está disponible. Por favor elige otra..
        /// </summary>
        public static string Partidas_NoDisponibleMensaje {
            get {
                return ResourceManager.GetString("Partidas_NoDisponibleMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida no disponible.
        /// </summary>
        public static string Partidas_NoDisponibleTitulo {
            get {
                return ResourceManager.GetString("Partidas_NoDisponibleTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu puntaje:.
        /// </summary>
        public static string Partidas_PuntajePrefijo {
            get {
                return ResourceManager.GetString("Partidas_PuntajePrefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay partidas disponibles en este momento..
        /// </summary>
        public static string Partidas_SinPartidas {
            get {
                return ResourceManager.GetString("Partidas_SinPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Únete a una partida o crea la tuya..
        /// </summary>
        public static string Partidas_Subtitulo {
            get {
                return ResourceManager.GetString("Partidas_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas en curso.
        /// </summary>
        public static string Partidas_Titulo {
            get {
                return ResourceManager.GetString("Partidas_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Partidas.
        /// </summary>
        public static string Partidas_TituloVentana {
            get {
                return ResourceManager.GetString("Partidas_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirme.
        /// </summary>
        public static string Partidas_Unirme {
            get {
                return ResourceManager.GetString("Partidas_Unirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver perfil.
        /// </summary>
        public static string Partidas_VerPerfil {
            get {
                return ResourceManager.GetString("Partidas_VerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandonaste una partida en curso. Se restaron de tu puntaje global:.
        /// </summary>
        public static string Penalizacion_Mensaje {
            get {
                return ResourceManager.GetString("Penalizacion_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntaje anterior.
        /// </summary>
        public static string Penalizacion_PuntajeAnterior {
            get {
                return ResourceManager.GetString("Penalizacion_PuntajeAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pts → {1} pts.
        /// </summary>
        public static string Penalizacion_PuntajeFormato {
            get {
                return ResourceManager.GetString("Penalizacion_PuntajeFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to –{0} pts.
        /// </summary>
        public static string Penalizacion_RestaFormato {
            get {
                return ResourceManager.GetString("Penalizacion_RestaFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalización aplicada.
        /// </summary>
        public static string Penalizacion_Titulo {
            get {
                return ResourceManager.GetString("Penalizacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sumaste puntos esta vez.
        /// </summary>
        public static string PerdedorAdivinador_Subtitulo {
            get {
                return ResourceManager.GetString("PerdedorAdivinador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se acabaron los intentos.
        /// </summary>
        public static string PerdedorAdivinador_Titulo {
            get {
                return ResourceManager.GetString("PerdedorAdivinador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No obtuviste puntos esta vez.
        /// </summary>
        public static string PerdedorCreador_Subtitulo {
            get {
                return ResourceManager.GetString("PerdedorCreador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu rival adivinó la palabra.
        /// </summary>
        public static string PerdedorCreador_Titulo {
            get {
                return ResourceManager.GetString("PerdedorCreador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        public static string Perfil_EditarPerfil {
            get {
                return ResourceManager.GetString("Perfil_EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIDAS GANADAS.
        /// </summary>
        public static string Perfil_PartidasGanadas {
            get {
                return ResourceManager.GetString("Perfil_PartidasGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENALIZACIONES.
        /// </summary>
        public static string Perfil_Penalizaciones {
            get {
                return ResourceManager.GetString("Perfil_Penalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNTAJE TOTAL.
        /// </summary>
        public static string Perfil_PuntajeTotal {
            get {
                return ResourceManager.GetString("Perfil_PuntajeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIVAL VENCIDO.
        /// </summary>
        public static string Perfil_RivalVencido {
            get {
                return ResourceManager.GetString("Perfil_RivalVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu información personal.
        /// </summary>
        public static string Perfil_Subtitulo {
            get {
                return ResourceManager.GetString("Perfil_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi perfil.
        /// </summary>
        public static string Perfil_Titulo {
            get {
                return ResourceManager.GetString("Perfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado · Mi perfil.
        /// </summary>
        public static string Perfil_TituloVentana {
            get {
                return ResourceManager.GetString("Perfil_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string RegistrarCuenta_ConfirmarContrasena {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ConfirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un número de celular válido (10 a 15 dígitos)..
        /// </summary>
        public static string RegistrarCuenta_ErrorCelularInvalido {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCelularInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no cumple los requisitos..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenaRequisitos {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenasNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo ya tiene una cuenta asociada..
        /// </summary>
        public static string RegistrarCuenta_ErrorCorreoExiste {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCorreoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa una fecha de nacimiento válida..
        /// </summary>
        public static string RegistrarCuenta_ErrorEdadMaxima {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorEdadMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes tener al menos 10 años cumplidos para registrarte..
        /// </summary>
        public static string RegistrarCuenta_ErrorEdadMinima {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorEdadMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona tu fecha de nacimiento..
        /// </summary>
        public static string RegistrarCuenta_ErrorFechaVacia {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorFechaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Cuenta creada con éxito! Ahora puedes iniciar sesión..
        /// </summary>
        public static string RegistrarCuenta_ExitoMensaje {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        public static string RegistrarCuenta_ExitoTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string RegistrarCuenta_FechaNacimiento {
            get {
                return ResourceManager.GetString("RegistrarCuenta_FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre completo.
        /// </summary>
        public static string RegistrarCuenta_NombreCompleto {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de celular.
        /// </summary>
        public static string RegistrarCuenta_NumeroCelular {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NumeroCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos 8 caracteres.
        /// </summary>
        public static string RegistrarCuenta_Req8 {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Req8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una letra mayúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMayuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una letra minúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMinuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un número.
        /// </summary>
        public static string RegistrarCuenta_ReqNumero {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU CONTRASEÑA DEBE TENER:.
        /// </summary>
        public static string RegistrarCuenta_RequisitosTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_RequisitosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo unos datos y ya puedes empezar a jugar..
        /// </summary>
        public static string RegistrarCuenta_Subtitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear una cuenta.
        /// </summary>
        public static string RegistrarCuenta_Titulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes cuenta?.
        /// </summary>
        public static string RegistrarCuenta_YaTienesCuenta {
            get {
                return ResourceManager.GetString("RegistrarCuenta_YaTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo reabrir la partida. Regresando al lobby..
        /// </summary>
        public static string RivalAbandono_ErrorReabrir {
            get {
                return ResourceManager.GetString("RivalAbandono_ErrorReabrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperar a otro oponente.
        /// </summary>
        public static string RivalAbandono_Esperar {
            get {
                return ResourceManager.GetString("RivalAbandono_Esperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  abandonó la partida..
        /// </summary>
        public static string RivalAbandono_MensajeSufijo {
            get {
                return ResourceManager.GetString("RivalAbandono_MensajeSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Se le aplicará una penalización por su cuenta..
        /// </summary>
        public static string RivalAbandono_Penalizacion {
            get {
                return ResourceManager.GetString("RivalAbandono_Penalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Volver al lobby?.
        /// </summary>
        public static string RivalAbandono_Pregunta {
            get {
                return ResourceManager.GetString("RivalAbandono_Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu rival abandonó.
        /// </summary>
        public static string RivalAbandono_Titulo {
            get {
                return ResourceManager.GetString("RivalAbandono_Titulo", resourceCulture);
            }
        }
    }
}
