//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteAhorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí, abandonar.
        /// </summary>
        public static string Abandonar_Confirmar {
            get {
                return ResourceManager.GetString("Abandonar_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 puntos.
        /// </summary>
        public static string Abandonar_Puntos {
            get {
                return ResourceManager.GetString("Abandonar_Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si abandonas se te restarán.
        /// </summary>
        public static string Abandonar_TextoAntes {
            get {
                return ResourceManager.GetString("Abandonar_TextoAntes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de tu puntaje global y se cancelará la partida para ambos jugadores..
        /// </summary>
        public static string Abandonar_TextoDespues {
            get {
                return ResourceManager.GetString("Abandonar_TextoDespues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Abandonar la partida?.
        /// </summary>
        public static string Abandonar_Titulo {
            get {
                return ResourceManager.GetString("Abandonar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la partida.
        /// </summary>
        public static string Abandonar_Volver {
            get {
                return ResourceManager.GetString("Abandonar_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra a tu cuenta para guardar tu progreso, o crea una cuenta gratis para empezar a jugar..
        /// </summary>
        public static string Bienvenida_Descripcion {
            get {
                return ResourceManager.GetString("Bienvenida_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 intentos.
        /// </summary>
        public static string Bienvenida_Intentos {
            get {
                return ResourceManager.GetString("Bienvenida_Intentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A_O__A__.
        /// </summary>
        public static string Bienvenida_PalabraDecorativa {
            get {
                return ResourceManager.GetString("Bienvenida_PalabraDecorativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivina la palabra letra por letra antes de quedarte sin intentos..
        /// </summary>
        public static string Bienvenida_Subtitulo {
            get {
                return ResourceManager.GetString("Bienvenida_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El Ahorcado!.
        /// </summary>
        public static string Bienvenida_Titulo {
            get {
                return ResourceManager.GetString("Bienvenida_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string CambiarContrasena_ContrasenaActual {
            get {
                return ResourceManager.GetString("CambiarContrasena_ContrasenaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual es incorrecta..
        /// </summary>
        public static string CambiarContrasena_ErrorActualIncorrecta {
            get {
                return ResourceManager.GetString("CambiarContrasena_ErrorActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu contraseña actual..
        /// </summary>
        public static string CambiarContrasena_ErrorActualVacia {
            get {
                return ResourceManager.GetString("CambiarContrasena_ErrorActualVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña se cambió correctamente..
        /// </summary>
        public static string CambiarContrasena_ExitoMensaje {
            get {
                return ResourceManager.GetString("CambiarContrasena_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actualizada.
        /// </summary>
        public static string CambiarContrasena_ExitoTitulo {
            get {
                return ResourceManager.GetString("CambiarContrasena_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string CambiarContrasena_NuevaContrasena {
            get {
                return ResourceManager.GetString("CambiarContrasena_NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por seguridad, ingresa tu contraseña actual para continuar..
        /// </summary>
        public static string CambiarContrasena_Paso1 {
            get {
                return ResourceManager.GetString("CambiarContrasena_Paso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu nueva contraseña..
        /// </summary>
        public static string CambiarContrasena_Paso2 {
            get {
                return ResourceManager.GetString("CambiarContrasena_Paso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string CambiarContrasena_Titulo {
            get {
                return ResourceManager.GetString("CambiarContrasena_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Comun_Aceptar {
            get {
                return ResourceManager.GetString("Comun_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es obligatorio..
        /// </summary>
        public static string Comun_CampoObligatorio {
            get {
                return ResourceManager.GetString("Comun_CampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Comun_Cancelar {
            get {
                return ResourceManager.GetString("Comun_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Comun_Categoria {
            get {
                return ResourceManager.GetString("Comun_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 💬  Chat.
        /// </summary>
        public static string Comun_Chat {
            get {
                return ResourceManager.GetString("Comun_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string Comun_Continuar {
            get {
                return ResourceManager.GetString("Comun_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Comun_Contrasena {
            get {
                return ResourceManager.GetString("Comun_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Comun_CorreoElectronico {
            get {
                return ResourceManager.GetString("Comun_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Comun_Error {
            get {
                return ResourceManager.GetString("Comun_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un correo electrónico válido..
        /// </summary>
        public static string comun_ErrorCorreoInvalido {
            get {
                return ResourceManager.GetString("comun_ErrorCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} pts.
        /// </summary>
        public static string Comun_FormatoPuntos {
            get {
                return ResourceManager.GetString("Comun_FormatoPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +{0} pts.
        /// </summary>
        public static string Comun_FormatoPuntosPositivos {
            get {
                return ResourceManager.GetString("Comun_FormatoPuntosPositivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Comun_Guardar {
            get {
                return ResourceManager.GetString("Comun_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Comun_IniciarSesion {
            get {
                return ResourceManager.GetString("Comun_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión.
        /// </summary>
        public static string Comun_IniciaSesion {
            get {
                return ResourceManager.GetString("Comun_IniciaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al lobby.
        /// </summary>
        public static string Comun_IrAlLobby {
            get {
                return ResourceManager.GetString("Comun_IrAlLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar de nuevo.
        /// </summary>
        public static string Comun_JugarDeNuevo {
            get {
                return ResourceManager.GetString("Comun_JugarDeNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palabra.
        /// </summary>
        public static string Comun_Palabra {
            get {
                return ResourceManager.GetString("Comun_Palabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje global.
        /// </summary>
        public static string Comun_PuntajeGlobal {
            get {
                return ResourceManager.GetString("Comun_PuntajeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos obtenidos.
        /// </summary>
        public static string Comun_PuntosObtenidos {
            get {
                return ResourceManager.GetString("Comun_PuntosObtenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta.
        /// </summary>
        public static string Comun_RegistrarCuenta {
            get {
                return ResourceManager.GetString("Comun_RegistrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string Comun_Registrate {
            get {
                return ResourceManager.GetString("Comun_Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rival.
        /// </summary>
        public static string Comun_Rival {
            get {
                return ResourceManager.GetString("Comun_Rival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Comun_Salir {
            get {
                return ResourceManager.GetString("Comun_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⇐ Volver.
        /// </summary>
        public static string Comun_Volver {
            get {
                return ResourceManager.GetString("Comun_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres jugar otra partida con .
        /// </summary>
        public static string DialogoResultado_PreguntaPrefijo {
            get {
                return ResourceManager.GetString("DialogoResultado_PreguntaPrefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ?.
        /// </summary>
        public static string DialogoResultado_PreguntaSufijo {
            get {
                return ResourceManager.GetString("DialogoResultado_PreguntaSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string EditarPerfil_CambiarContrasena {
            get {
                return ResourceManager.GetString("EditarPerfil_CambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITANDO.
        /// </summary>
        public static string EditarPerfil_Editando {
            get {
                return ResourceManager.GetString("EditarPerfil_Editando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener 8+ caracteres, mayúscula, minúscula y número..
        /// </summary>
        public static string EditarPerfil_ErrorContrasenaRequisitos {
            get {
                return ResourceManager.GetString("EditarPerfil_ErrorContrasenaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus cambios se guardaron correctamente..
        /// </summary>
        public static string EditarPerfil_ExitoMensaje {
            get {
                return ResourceManager.GetString("EditarPerfil_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil actualizado.
        /// </summary>
        public static string EditarPerfil_ExitoTitulo {
            get {
                return ResourceManager.GetString("EditarPerfil_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string EditarPerfil_GuardarCambios {
            get {
                return ResourceManager.GetString("EditarPerfil_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña (opcional).
        /// </summary>
        public static string EditarPerfil_NuevaContrasena {
            get {
                return ResourceManager.GetString("EditarPerfil_NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualiza tus datos (el correo no puede cambiarse).
        /// </summary>
        public static string EditarPerfil_Subtitulo {
            get {
                return ResourceManager.GetString("EditarPerfil_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string EditarPerfil_Titulo {
            get {
                return ResourceManager.GetString("EditarPerfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Editar perfil.
        /// </summary>
        public static string EditarPerfil_TituloVentana {
            get {
                return ResourceManager.GetString("EditarPerfil_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar ⇒.
        /// </summary>
        public static string ElegirCategoria_Continuar {
            get {
                return ResourceManager.GetString("ElegirCategoria_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige una categoría para continuar..
        /// </summary>
        public static string ElegirCategoria_ErrorMensaje {
            get {
                return ResourceManager.GetString("ElegirCategoria_ErrorMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1 de 2 · Elige una categoría.
        /// </summary>
        public static string ElegirCategoria_Paso {
            get {
                return ResourceManager.GetString("ElegirCategoria_Paso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Elegir categoría.
        /// </summary>
        public static string ElegirCategoria_TituloVentana {
            get {
                return ResourceManager.GetString("ElegirCategoria_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría: {0}.
        /// </summary>
        public static string ElegirPalabra_CategoriaConNombre {
            get {
                return ResourceManager.GetString("ElegirPalabra_CategoriaConNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar palabra.
        /// </summary>
        public static string ElegirPalabra_Confirmar {
            get {
                return ResourceManager.GetString("ElegirPalabra_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige una palabra para continuar..
        /// </summary>
        public static string ElegirPalabra_ErrorMensaje {
            get {
                return ResourceManager.GetString("ElegirPalabra_ErrorMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  letras.
        /// </summary>
        public static string ElegirPalabra_LetrasSufijo {
            get {
                return ResourceManager.GetString("ElegirPalabra_LetrasSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2 de 2 · Elige una palabra.
        /// </summary>
        public static string ElegirPalabra_Paso {
            get {
                return ResourceManager.GetString("ElegirPalabra_Paso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Elegir palabra.
        /// </summary>
        public static string ElegirPalabra_TituloVentana {
            get {
                return ResourceManager.GetString("ElegirPalabra_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  {0}.
        /// </summary>
        public static string EsperandoPalabra_CreadorBoton {
            get {
                return ResourceManager.GetString("EsperandoPalabra_CreadorBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} está eligiendo la palabra....
        /// </summary>
        public static string EsperandoPalabra_Eligiendo {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Eligiendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuando termine, comenzarás a adivinar. Te avisaremos en cuanto la palabra esté lista..
        /// </summary>
        public static string EsperandoPalabra_Instruccion {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Instruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu rival está eligiendo la palabra que tendrás que adivinar.
        /// </summary>
        public static string EsperandoPalabra_Subtitulo {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Te uniste a la partida!.
        /// </summary>
        public static string EsperandoPalabra_TeUniste {
            get {
                return ResourceManager.GetString("EsperandoPalabra_TeUniste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Esperando palabra.
        /// </summary>
        public static string EsperandoPalabra_TituloVentana {
            get {
                return ResourceManager.GetString("EsperandoPalabra_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú.
        /// </summary>
        public static string EsperandoPalabra_TuBoton {
            get {
                return ResourceManager.GetString("EsperandoPalabra_TuBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vs.
        /// </summary>
        public static string EsperandoPalabra_Vs {
            get {
                return ResourceManager.GetString("EsperandoPalabra_Vs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar partida.
        /// </summary>
        public static string EsperandoRival_CancelarPartida {
            get {
                return ResourceManager.GetString("EsperandoRival_CancelarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas cancelar la partida?.
        /// </summary>
        public static string EsperandoRival_ConfirmarCancelar {
            get {
                return ResourceManager.GetString("EsperandoRival_ConfirmarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu partida aparece en la lista del lobby. En cuanto alguien se una, podrás elegir la palabra que tendrá que adivinar..
        /// </summary>
        public static string EsperandoRival_Descripcion {
            get {
                return ResourceManager.GetString("EsperandoRival_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu partida está lista.
        /// </summary>
        public static string EsperandoRival_Encabezado {
            get {
                return ResourceManager.GetString("EsperandoRival_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ···  Esperando....
        /// </summary>
        public static string EsperandoRival_Esperando {
            get {
                return ResourceManager.GetString("EsperandoRival_Esperando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartiendo en el lobby para que alguien se una.
        /// </summary>
        public static string EsperandoRival_Subtitulo {
            get {
                return ResourceManager.GetString("EsperandoRival_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIEMPO EN ESPERA.
        /// </summary>
        public static string EsperandoRival_TiempoEnEspera {
            get {
                return ResourceManager.GetString("EsperandoRival_TiempoEnEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a un rival....
        /// </summary>
        public static string EsperandoRival_Titulo {
            get {
                return ResourceManager.GetString("EsperandoRival_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Esperando oponente.
        /// </summary>
        public static string EsperandoRival_TituloVentana {
            get {
                return ResourceManager.GetString("EsperandoRival_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú.
        /// </summary>
        public static string EsperandoRival_Tu {
            get {
                return ResourceManager.GetString("EsperandoRival_Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganaste +10 puntos por esta partida.
        /// </summary>
        public static string GanadorAdivinador_Subtitulo {
            get {
                return ResourceManager.GetString("GanadorAdivinador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Adivinaste la palabra!.
        /// </summary>
        public static string GanadorAdivinador_Titulo {
            get {
                return ResourceManager.GetString("GanadorAdivinador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganaste +5 puntos por crear la partida.
        /// </summary>
        public static string GanadorCreador_Subtitulo {
            get {
                return ResourceManager.GetString("GanadorCreador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu rival no pudo adivinar.
        /// </summary>
        public static string GanadorCreador_Titulo {
            get {
                return ResourceManager.GetString("GanadorCreador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas ganadas ({0}).
        /// </summary>
        public static string Historial_BtnGanadas {
            get {
                return ResourceManager.GetString("Historial_BtnGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Penalizaciones ({0}).
        /// </summary>
        public static string Historial_BtnPenalizaciones {
            get {
                return ResourceManager.GetString("Historial_BtnPenalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rival no adivinó ({0}).
        /// </summary>
        public static string Historial_BtnRival {
            get {
                return ResourceManager.GetString("Historial_BtnRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA.
        /// </summary>
        public static string Historial_ColFecha {
            get {
                return ResourceManager.GetString("Historial_ColFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PALABRA ADIVINADA.
        /// </summary>
        public static string Historial_ColPalabraGanadas {
            get {
                return ResourceManager.GetString("Historial_ColPalabraGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PALABRA EN JUEGO.
        /// </summary>
        public static string Historial_ColPalabraPenal {
            get {
                return ResourceManager.GetString("Historial_ColPalabraPenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PALABRA ELEGIDA.
        /// </summary>
        public static string Historial_ColPalabraRival {
            get {
                return ResourceManager.GetString("Historial_ColPalabraRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PUNTOS.
        /// </summary>
        public static string Historial_ColPuntos {
            get {
                return ResourceManager.GetString("Historial_ColPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIVAL VENCIDO.
        /// </summary>
        public static string Historial_ColRivalGanadas {
            get {
                return ResourceManager.GetString("Historial_ColRivalGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTIDA ABANDONADA.
        /// </summary>
        public static string Historial_ColRivalPenal {
            get {
                return ResourceManager.GetString("Historial_ColRivalPenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIVAL QUE FALLÓ.
        /// </summary>
        public static string Historial_ColRivalRival {
            get {
                return ResourceManager.GetString("Historial_ColRivalRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GANADAS.
        /// </summary>
        public static string Historial_Ganadas {
            get {
                return ResourceManager.GetString("Historial_Ganadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PENALIZACIONES.
        /// </summary>
        public static string Historial_Penalizaciones {
            get {
                return ResourceManager.GetString("Historial_Penalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  pts.
        /// </summary>
        public static string Historial_PtsSufijo {
            get {
                return ResourceManager.GetString("Historial_PtsSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PUNTAJE GLOBAL.
        /// </summary>
        public static string Historial_PuntajeGlobalEtiqueta {
            get {
                return ResourceManager.GetString("Historial_PuntajeGlobalEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +{0} pts.
        /// </summary>
        public static string Historial_PuntosGanados {
            get {
                return ResourceManager.GetString("Historial_PuntosGanados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a –{0} pts.
        /// </summary>
        public static string Historial_PuntosPerdidos {
            get {
                return ResourceManager.GetString("Historial_PuntosPerdidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIVAL NO ADIVINÓ.
        /// </summary>
        public static string Historial_RivalNoAdivino {
            get {
                return ResourceManager.GetString("Historial_RivalNoAdivino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros en esta categoría..
        /// </summary>
        public static string Historial_SinRegistros {
            get {
                return ResourceManager.GetString("Historial_SinRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu progreso, partida por partida.
        /// </summary>
        public static string Historial_Subtitulo {
            get {
                return ResourceManager.GetString("Historial_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de puntajes.
        /// </summary>
        public static string Historial_Titulo {
            get {
                return ResourceManager.GetString("Historial_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Historial.
        /// </summary>
        public static string Historial_TituloVentana {
            get {
                return ResourceManager.GetString("Historial_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña que ingresaste es incorrecta..
        /// </summary>
        public static string IniciarSesion_ErrorContrasena {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu contraseña..
        /// </summary>
        public static string IniciarSesion_ErrorContrasenaVacia {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasenaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo electrónico no existe..
        /// </summary>
        public static string IniciarSesion_ErrorCorreo {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo electrónico..
        /// </summary>
        public static string IniciarSesion_ErrorCorreoVacio {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string IniciarSesion_NoTienesCuenta {
            get {
                return ResourceManager.GetString("IniciarSesion_NoTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido de vuelta.
        /// </summary>
        public static string IniciarSesion_Subtitulo {
            get {
                return ResourceManager.GetString("IniciarSesion_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar partida.
        /// </summary>
        public static string Juego_AbandonarPartida {
            get {
                return ResourceManager.GetString("Juego_AbandonarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CATEGORÍA.
        /// </summary>
        public static string Juego_CategoriaEtiqueta {
            get {
                return ResourceManager.GetString("Juego_CategoriaEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas abandonar la partida? Perderás puntos..
        /// </summary>
        public static string Juego_ConfirmarAbandono {
            get {
                return ResourceManager.GetString("Juego_ConfirmarAbandono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DESCRIPCIÓN.
        /// </summary>
        public static string Juego_DescripcionEtiqueta {
            get {
                return ResourceManager.GetString("Juego_DescripcionEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando que el creador elija la palabra....
        /// </summary>
        public static string Juego_EsperandoPalabra {
            get {
                return ResourceManager.GetString("Juego_EsperandoPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}  intentos restantes.
        /// </summary>
        public static string Juego_IntentosRestantes {
            get {
                return ResourceManager.GetString("Juego_IntentosRestantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LETRAS INCORRECTAS:  .
        /// </summary>
        public static string Juego_LetrasIncorrectas {
            get {
                return ResourceManager.GetString("Juego_LetrasIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} abandonó la partida. Regresarás al lobby..
        /// </summary>
        public static string Juego_RivalAbandonoMensaje {
            get {
                return ResourceManager.GetString("Juego_RivalAbandonoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rival abandonó.
        /// </summary>
        public static string Juego_RivalAbandonoTitulo {
            get {
                return ResourceManager.GetString("Juego_RivalAbandonoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rival está adivinando.
        /// </summary>
        public static string Juego_RivalAdivinando {
            get {
                return ResourceManager.GetString("Juego_RivalAdivinando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Partida en curso.
        /// </summary>
        public static string Juego_TituloVentana {
            get {
                return ResourceManager.GetString("Juego_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú (adivinando).
        /// </summary>
        public static string Juego_TuAdivinando {
            get {
                return ResourceManager.GetString("Juego_TuAdivinando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú (creador).
        /// </summary>
        public static string Juego_TuCreador {
            get {
                return ResourceManager.GetString("Juego_TuCreador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TU PALABRA:  .
        /// </summary>
        public static string Juego_TuPalabra {
            get {
                return ResourceManager.GetString("Juego_TuPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu rival.
        /// </summary>
        public static string Juego_TuRival {
            get {
                return ResourceManager.GetString("Juego_TuRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vs {0}.
        /// </summary>
        public static string Juego_VsRival {
            get {
                return ResourceManager.GetString("Juego_VsRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string Partidas_CerrarSesion {
            get {
                return ResourceManager.GetString("Partidas_CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREADA.
        /// </summary>
        public static string Partidas_ColCreada {
            get {
                return ResourceManager.GetString("Partidas_ColCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREADOR.
        /// </summary>
        public static string Partidas_ColCreador {
            get {
                return ResourceManager.GetString("Partidas_ColCreador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Partidas_ColIdioma {
            get {
                return ResourceManager.GetString("Partidas_ColIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUGADORES.
        /// </summary>
        public static string Partidas_ColJugadores {
            get {
                return ResourceManager.GetString("Partidas_ColJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas cerrar sesión?.
        /// </summary>
        public static string Partidas_ConfirmarCerrarMensaje {
            get {
                return ResourceManager.GetString("Partidas_ConfirmarCerrarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Crear partida.
        /// </summary>
        public static string Partidas_CrearPartida {
            get {
                return ResourceManager.GetString("Partidas_CrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a partidas disponibles.
        /// </summary>
        public static string Partidas_DisponiblesSufijo {
            get {
                return ResourceManager.GetString("Partidas_DisponiblesSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a · Cada partida es de 2 jugadores.
        /// </summary>
        public static string Partidas_DosJugadores {
            get {
                return ResourceManager.GetString("Partidas_DosJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con base de datos, inténtelo más tarde..
        /// </summary>
        public static string Partidas_ErrorConexion {
            get {
                return ResourceManager.GetString("Partidas_ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de puntajes.
        /// </summary>
        public static string Partidas_HistorialPuntajes {
            get {
                return ResourceManager.GetString("Partidas_HistorialPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Partidas_IdiomaPartidaEspanol {
            get {
                return ResourceManager.GetString("Partidas_IdiomaPartidaEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string Partidas_IdiomaPartidaIngles {
            get {
                return ResourceManager.GetString("Partidas_IdiomaPartidaIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta partida ya no está disponible. Por favor elige otra..
        /// </summary>
        public static string Partidas_NoDisponibleMensaje {
            get {
                return ResourceManager.GetString("Partidas_NoDisponibleMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida no disponible.
        /// </summary>
        public static string Partidas_NoDisponibleTitulo {
            get {
                return ResourceManager.GetString("Partidas_NoDisponibleTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu puntaje:.
        /// </summary>
        public static string Partidas_PuntajePrefijo {
            get {
                return ResourceManager.GetString("Partidas_PuntajePrefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay partidas disponibles en este momento..
        /// </summary>
        public static string Partidas_SinPartidas {
            get {
                return ResourceManager.GetString("Partidas_SinPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Únete a una partida o crea la tuya..
        /// </summary>
        public static string Partidas_Subtitulo {
            get {
                return ResourceManager.GetString("Partidas_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas en curso.
        /// </summary>
        public static string Partidas_Titulo {
            get {
                return ResourceManager.GetString("Partidas_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Partidas.
        /// </summary>
        public static string Partidas_TituloVentana {
            get {
                return ResourceManager.GetString("Partidas_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirme.
        /// </summary>
        public static string Partidas_Unirme {
            get {
                return ResourceManager.GetString("Partidas_Unirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil.
        /// </summary>
        public static string Partidas_VerPerfil {
            get {
                return ResourceManager.GetString("Partidas_VerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonaste una partida en curso. Se restaron de tu puntaje global:.
        /// </summary>
        public static string Penalizacion_Mensaje {
            get {
                return ResourceManager.GetString("Penalizacion_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje anterior.
        /// </summary>
        public static string Penalizacion_PuntajeAnterior {
            get {
                return ResourceManager.GetString("Penalizacion_PuntajeAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} pts → {1} pts.
        /// </summary>
        public static string Penalizacion_PuntajeFormato {
            get {
                return ResourceManager.GetString("Penalizacion_PuntajeFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a –{0} pts.
        /// </summary>
        public static string Penalizacion_RestaFormato {
            get {
                return ResourceManager.GetString("Penalizacion_RestaFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Penalización aplicada.
        /// </summary>
        public static string Penalizacion_Titulo {
            get {
                return ResourceManager.GetString("Penalizacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No sumaste puntos esta vez.
        /// </summary>
        public static string PerdedorAdivinador_Subtitulo {
            get {
                return ResourceManager.GetString("PerdedorAdivinador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se acabaron los intentos.
        /// </summary>
        public static string PerdedorAdivinador_Titulo {
            get {
                return ResourceManager.GetString("PerdedorAdivinador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No obtuviste puntos esta vez.
        /// </summary>
        public static string PerdedorCreador_Subtitulo {
            get {
                return ResourceManager.GetString("PerdedorCreador_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu rival adivinó la palabra.
        /// </summary>
        public static string PerdedorCreador_Titulo {
            get {
                return ResourceManager.GetString("PerdedorCreador_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string Perfil_EditarPerfil {
            get {
                return ResourceManager.GetString("Perfil_EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTIDAS GANADAS.
        /// </summary>
        public static string Perfil_PartidasGanadas {
            get {
                return ResourceManager.GetString("Perfil_PartidasGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PENALIZACIONES.
        /// </summary>
        public static string Perfil_Penalizaciones {
            get {
                return ResourceManager.GetString("Perfil_Penalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PUNTAJE TOTAL.
        /// </summary>
        public static string Perfil_PuntajeTotal {
            get {
                return ResourceManager.GetString("Perfil_PuntajeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIVAL VENCIDO.
        /// </summary>
        public static string Perfil_RivalVencido {
            get {
                return ResourceManager.GetString("Perfil_RivalVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu información personal.
        /// </summary>
        public static string Perfil_Subtitulo {
            get {
                return ResourceManager.GetString("Perfil_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string Perfil_Titulo {
            get {
                return ResourceManager.GetString("Perfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Mi perfil.
        /// </summary>
        public static string Perfil_TituloVentana {
            get {
                return ResourceManager.GetString("Perfil_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string RegistrarCuenta_ConfirmarContrasena {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ConfirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un número de celular válido (10 a 15 dígitos)..
        /// </summary>
        public static string RegistrarCuenta_ErrorCelularInvalido {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCelularInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no cumple los requisitos..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenaRequisitos {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenasNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo ya tiene una cuenta asociada..
        /// </summary>
        public static string RegistrarCuenta_ErrorCorreoExiste {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCorreoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa una fecha de nacimiento válida..
        /// </summary>
        public static string RegistrarCuenta_ErrorEdadMaxima {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorEdadMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes tener al menos 10 años cumplidos para registrarte..
        /// </summary>
        public static string RegistrarCuenta_ErrorEdadMinima {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorEdadMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona tu fecha de nacimiento..
        /// </summary>
        public static string RegistrarCuenta_ErrorFechaVacia {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorFechaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada con éxito! Ahora puedes iniciar sesión..
        /// </summary>
        public static string RegistrarCuenta_ExitoMensaje {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro exitoso.
        /// </summary>
        public static string RegistrarCuenta_ExitoTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string RegistrarCuenta_FechaNacimiento {
            get {
                return ResourceManager.GetString("RegistrarCuenta_FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string RegistrarCuenta_NombreCompleto {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de celular.
        /// </summary>
        public static string RegistrarCuenta_NumeroCelular {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NumeroCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos 8 caracteres.
        /// </summary>
        public static string RegistrarCuenta_Req8 {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Req8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra mayúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMayuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra minúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMinuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un número.
        /// </summary>
        public static string RegistrarCuenta_ReqNumero {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TU CONTRASEÑA DEBE TENER:.
        /// </summary>
        public static string RegistrarCuenta_RequisitosTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_RequisitosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo unos datos y ya puedes empezar a jugar..
        /// </summary>
        public static string RegistrarCuenta_Subtitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una cuenta.
        /// </summary>
        public static string RegistrarCuenta_Titulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes cuenta?.
        /// </summary>
        public static string RegistrarCuenta_YaTienesCuenta {
            get {
                return ResourceManager.GetString("RegistrarCuenta_YaTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo reabrir la partida. Regresando al lobby..
        /// </summary>
        public static string RivalAbandono_ErrorReabrir {
            get {
                return ResourceManager.GetString("RivalAbandono_ErrorReabrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperar a otro oponente.
        /// </summary>
        public static string RivalAbandono_Esperar {
            get {
                return ResourceManager.GetString("RivalAbandono_Esperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  abandonó la partida. Se le aplicará una penalización por su cuenta..
        /// </summary>
        public static string RivalAbandono_MensajeSufijo {
            get {
                return ResourceManager.GetString("RivalAbandono_MensajeSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué te gustaría hacer ahora?.
        /// </summary>
        public static string RivalAbandono_Pregunta {
            get {
                return ResourceManager.GetString("RivalAbandono_Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu rival abandonó.
        /// </summary>
        public static string RivalAbandono_Titulo {
            get {
                return ResourceManager.GetString("RivalAbandono_Titulo", resourceCulture);
            }
        }
    }
}
