//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteAhorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra a tu cuenta para guardar tu progreso, o crea una cuenta gratis para empezar a jugar..
        /// </summary>
        public static string Bienvenida_Descripcion {
            get {
                return ResourceManager.GetString("Bienvenida_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 intentos.
        /// </summary>
        public static string Bienvenida_Intentos {
            get {
                return ResourceManager.GetString("Bienvenida_Intentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A_O__A__.
        /// </summary>
        public static string Bienvenida_PalabraDecorativa {
            get {
                return ResourceManager.GetString("Bienvenida_PalabraDecorativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivina la palabra letra por letra antes de quedarte sin intentos..
        /// </summary>
        public static string Bienvenida_Subtitulo {
            get {
                return ResourceManager.GetString("Bienvenida_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El Ahorcado!.
        /// </summary>
        public static string Bienvenida_Titulo {
            get {
                return ResourceManager.GetString("Bienvenida_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Comun_Contrasena {
            get {
                return ResourceManager.GetString("Comun_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Comun_CorreoElectronico {
            get {
                return ResourceManager.GetString("Comun_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Comun_IniciarSesion {
            get {
                return ResourceManager.GetString("Comun_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta.
        /// </summary>
        public static string Comun_RegistrarCuenta {
            get {
                return ResourceManager.GetString("Comun_RegistrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string Comun_Registrate {
            get {
                return ResourceManager.GetString("Comun_Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⇐ Volver.
        /// </summary>
        public static string Comun_Volver {
            get {
                return ResourceManager.GetString("Comun_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña que ingresaste es incorrecta..
        /// </summary>
        public static string IniciarSesion_ErrorContrasena {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ingresado no está conectado a una cuenta..
        /// </summary>
        public static string IniciarSesion_ErrorCorreo {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string IniciarSesion_NoTienesCuenta {
            get {
                return ResourceManager.GetString("IniciarSesion_NoTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido de vuelta.
        /// </summary>
        public static string IniciarSesion_Subtitulo {
            get {
                return ResourceManager.GetString("IniciarSesion_Subtitulo", resourceCulture);
            }
        }
    }
}
