//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteAhorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra a tu cuenta para guardar tu progreso, o crea una cuenta gratis para empezar a jugar..
        /// </summary>
        public static string Bienvenida_Descripcion {
            get {
                return ResourceManager.GetString("Bienvenida_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 intentos.
        /// </summary>
        public static string Bienvenida_Intentos {
            get {
                return ResourceManager.GetString("Bienvenida_Intentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A_O__A__.
        /// </summary>
        public static string Bienvenida_PalabraDecorativa {
            get {
                return ResourceManager.GetString("Bienvenida_PalabraDecorativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivina la palabra letra por letra antes de quedarte sin intentos..
        /// </summary>
        public static string Bienvenida_Subtitulo {
            get {
                return ResourceManager.GetString("Bienvenida_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El Ahorcado!.
        /// </summary>
        public static string Bienvenida_Titulo {
            get {
                return ResourceManager.GetString("Bienvenida_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es obligatorio..
        /// </summary>
        public static string Comun_CampoObligatorio {
            get {
                return ResourceManager.GetString("Comun_CampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Comun_Contrasena {
            get {
                return ResourceManager.GetString("Comun_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Comun_CorreoElectronico {
            get {
                return ResourceManager.GetString("Comun_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Comun_IniciarSesion {
            get {
                return ResourceManager.GetString("Comun_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión.
        /// </summary>
        public static string Comun_IniciaSesion {
            get {
                return ResourceManager.GetString("Comun_IniciaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta.
        /// </summary>
        public static string Comun_RegistrarCuenta {
            get {
                return ResourceManager.GetString("Comun_RegistrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string Comun_Registrate {
            get {
                return ResourceManager.GetString("Comun_Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⇐ Volver.
        /// </summary>
        public static string Comun_Volver {
            get {
                return ResourceManager.GetString("Comun_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña que ingresaste es incorrecta..
        /// </summary>
        public static string IniciarSesion_ErrorContrasena {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ingresado no está conectado a una cuenta..
        /// </summary>
        public static string IniciarSesion_ErrorCorreo {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string IniciarSesion_NoTienesCuenta {
            get {
                return ResourceManager.GetString("IniciarSesion_NoTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido de vuelta.
        /// </summary>
        public static string IniciarSesion_Subtitulo {
            get {
                return ResourceManager.GetString("IniciarSesion_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string RegistrarCuenta_ConfirmarContrasena {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ConfirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un número de celular válido (10 a 15 dígitos)..
        /// </summary>
        public static string RegistrarCuenta_ErrorCelularInvalido {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCelularInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no cumple los requisitos..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenaRequisitos {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenasNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo ya tiene una cuenta asociada..
        /// </summary>
        public static string RegistrarCuenta_ErrorCorreoExiste {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCorreoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un correo electrónico válido..
        /// </summary>
        public static string RegistrarCuenta_ErrorCorreoInvalido {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes tener al menos 10 años cumplidos para registrarte..
        /// </summary>
        public static string RegistrarCuenta_ErrorEdadMinima {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorEdadMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona tu fecha de nacimiento..
        /// </summary>
        public static string RegistrarCuenta_ErrorFechaVacia {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorFechaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada con éxito! Ahora puedes iniciar sesión..
        /// </summary>
        public static string RegistrarCuenta_ExitoMensaje {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro exitoso.
        /// </summary>
        public static string RegistrarCuenta_ExitoTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string RegistrarCuenta_FechaNacimiento {
            get {
                return ResourceManager.GetString("RegistrarCuenta_FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string RegistrarCuenta_NombreCompleto {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de celular.
        /// </summary>
        public static string RegistrarCuenta_NumeroCelular {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NumeroCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos 8 caracteres.
        /// </summary>
        public static string RegistrarCuenta_Req8 {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Req8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra mayúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMayuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra minúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMinuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un número.
        /// </summary>
        public static string RegistrarCuenta_ReqNumero {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TU CONTRASEÑA DEBE TENER:.
        /// </summary>
        public static string RegistrarCuenta_RequisitosTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_RequisitosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo unos datos y ya puedes empezar a jugar..
        /// </summary>
        public static string RegistrarCuenta_Subtitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una cuenta.
        /// </summary>
        public static string RegistrarCuenta_Titulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes cuenta?.
        /// </summary>
        public static string RegistrarCuenta_YaTienesCuenta {
            get {
                return ResourceManager.GetString("RegistrarCuenta_YaTienesCuenta", resourceCulture);
            }
        }
    }
}
