//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteAhorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí, abandonar.
        /// </summary>
        public static string Abandonar_Confirmar {
            get {
                return ResourceManager.GetString("Abandonar_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 puntos.
        /// </summary>
        public static string Abandonar_Puntos {
            get {
                return ResourceManager.GetString("Abandonar_Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si abandonas se te restarán.
        /// </summary>
        public static string Abandonar_TextoAntes {
            get {
                return ResourceManager.GetString("Abandonar_TextoAntes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de tu puntaje global y se cancelará la partida para ambos jugadores..
        /// </summary>
        public static string Abandonar_TextoDespues {
            get {
                return ResourceManager.GetString("Abandonar_TextoDespues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Abandonar la partida?.
        /// </summary>
        public static string Abandonar_Titulo {
            get {
                return ResourceManager.GetString("Abandonar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la partida.
        /// </summary>
        public static string Abandonar_Volver {
            get {
                return ResourceManager.GetString("Abandonar_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra a tu cuenta para guardar tu progreso, o crea una cuenta gratis para empezar a jugar..
        /// </summary>
        public static string Bienvenida_Descripcion {
            get {
                return ResourceManager.GetString("Bienvenida_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 intentos.
        /// </summary>
        public static string Bienvenida_Intentos {
            get {
                return ResourceManager.GetString("Bienvenida_Intentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A_O__A__.
        /// </summary>
        public static string Bienvenida_PalabraDecorativa {
            get {
                return ResourceManager.GetString("Bienvenida_PalabraDecorativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivina la palabra letra por letra antes de quedarte sin intentos..
        /// </summary>
        public static string Bienvenida_Subtitulo {
            get {
                return ResourceManager.GetString("Bienvenida_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El Ahorcado!.
        /// </summary>
        public static string Bienvenida_Titulo {
            get {
                return ResourceManager.GetString("Bienvenida_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es obligatorio..
        /// </summary>
        public static string Comun_CampoObligatorio {
            get {
                return ResourceManager.GetString("Comun_CampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Comun_Cancelar {
            get {
                return ResourceManager.GetString("Comun_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Comun_Contrasena {
            get {
                return ResourceManager.GetString("Comun_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Comun_CorreoElectronico {
            get {
                return ResourceManager.GetString("Comun_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Comun_Error {
            get {
                return ResourceManager.GetString("Comun_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Comun_IniciarSesion {
            get {
                return ResourceManager.GetString("Comun_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión.
        /// </summary>
        public static string Comun_IniciaSesion {
            get {
                return ResourceManager.GetString("Comun_IniciaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta.
        /// </summary>
        public static string Comun_RegistrarCuenta {
            get {
                return ResourceManager.GetString("Comun_RegistrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string Comun_Registrate {
            get {
                return ResourceManager.GetString("Comun_Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⇐ Volver.
        /// </summary>
        public static string Comun_Volver {
            get {
                return ResourceManager.GetString("Comun_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITANDO.
        /// </summary>
        public static string EditarPerfil_Editando {
            get {
                return ResourceManager.GetString("EditarPerfil_Editando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener 8+ caracteres, mayúscula, minúscula y número..
        /// </summary>
        public static string EditarPerfil_ErrorContrasenaRequisitos {
            get {
                return ResourceManager.GetString("EditarPerfil_ErrorContrasenaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus cambios se guardaron correctamente..
        /// </summary>
        public static string EditarPerfil_ExitoMensaje {
            get {
                return ResourceManager.GetString("EditarPerfil_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil actualizado.
        /// </summary>
        public static string EditarPerfil_ExitoTitulo {
            get {
                return ResourceManager.GetString("EditarPerfil_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string EditarPerfil_GuardarCambios {
            get {
                return ResourceManager.GetString("EditarPerfil_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña (opcional).
        /// </summary>
        public static string EditarPerfil_NuevaContrasena {
            get {
                return ResourceManager.GetString("EditarPerfil_NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualiza tus datos (el correo no puede cambiarse).
        /// </summary>
        public static string EditarPerfil_Subtitulo {
            get {
                return ResourceManager.GetString("EditarPerfil_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string EditarPerfil_Titulo {
            get {
                return ResourceManager.GetString("EditarPerfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Editar perfil.
        /// </summary>
        public static string EditarPerfil_TituloVentana {
            get {
                return ResourceManager.GetString("EditarPerfil_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar partida.
        /// </summary>
        public static string EsperandoRival_CancelarPartida {
            get {
                return ResourceManager.GetString("EsperandoRival_CancelarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas cancelar la partida?.
        /// </summary>
        public static string EsperandoRival_ConfirmarCancelar {
            get {
                return ResourceManager.GetString("EsperandoRival_ConfirmarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu partida aparece en la lista del lobby. En cuanto alguien se una, podrás elegir la palabra que tendrá que adivinar..
        /// </summary>
        public static string EsperandoRival_Descripcion {
            get {
                return ResourceManager.GetString("EsperandoRival_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu partida está lista.
        /// </summary>
        public static string EsperandoRival_Encabezado {
            get {
                return ResourceManager.GetString("EsperandoRival_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ···  Esperando....
        /// </summary>
        public static string EsperandoRival_Esperando {
            get {
                return ResourceManager.GetString("EsperandoRival_Esperando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartiendo en el lobby para que alguien se una.
        /// </summary>
        public static string EsperandoRival_Subtitulo {
            get {
                return ResourceManager.GetString("EsperandoRival_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIEMPO EN ESPERA.
        /// </summary>
        public static string EsperandoRival_TiempoEnEspera {
            get {
                return ResourceManager.GetString("EsperandoRival_TiempoEnEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a un rival....
        /// </summary>
        public static string EsperandoRival_Titulo {
            get {
                return ResourceManager.GetString("EsperandoRival_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Esperando oponente.
        /// </summary>
        public static string EsperandoRival_TituloVentana {
            get {
                return ResourceManager.GetString("EsperandoRival_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú.
        /// </summary>
        public static string EsperandoRival_Tu {
            get {
                return ResourceManager.GetString("EsperandoRival_Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña que ingresaste es incorrecta..
        /// </summary>
        public static string IniciarSesion_ErrorContrasena {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu contraseña..
        /// </summary>
        public static string IniciarSesion_ErrorContrasenaVacia {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorContrasenaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ingresado no está conectado a una cuenta..
        /// </summary>
        public static string IniciarSesion_ErrorCorreo {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo electrónico..
        /// </summary>
        public static string IniciarSesion_ErrorCorreoVacio {
            get {
                return ResourceManager.GetString("IniciarSesion_ErrorCorreoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string IniciarSesion_NoTienesCuenta {
            get {
                return ResourceManager.GetString("IniciarSesion_NoTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido de vuelta.
        /// </summary>
        public static string IniciarSesion_Subtitulo {
            get {
                return ResourceManager.GetString("IniciarSesion_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string Partidas_CerrarSesion {
            get {
                return ResourceManager.GetString("Partidas_CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREADA.
        /// </summary>
        public static string Partidas_ColCreada {
            get {
                return ResourceManager.GetString("Partidas_ColCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREADOR.
        /// </summary>
        public static string Partidas_ColCreador {
            get {
                return ResourceManager.GetString("Partidas_ColCreador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUGADORES.
        /// </summary>
        public static string Partidas_ColJugadores {
            get {
                return ResourceManager.GetString("Partidas_ColJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas cerrar sesión?.
        /// </summary>
        public static string Partidas_ConfirmarCerrarMensaje {
            get {
                return ResourceManager.GetString("Partidas_ConfirmarCerrarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Crear partida.
        /// </summary>
        public static string Partidas_CrearPartida {
            get {
                return ResourceManager.GetString("Partidas_CrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a partidas disponibles.
        /// </summary>
        public static string Partidas_DisponiblesSufijo {
            get {
                return ResourceManager.GetString("Partidas_DisponiblesSufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a · Cada partida es de 2 jugadores.
        /// </summary>
        public static string Partidas_DosJugadores {
            get {
                return ResourceManager.GetString("Partidas_DosJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con base de datos, inténtelo más tarde..
        /// </summary>
        public static string Partidas_ErrorConexion {
            get {
                return ResourceManager.GetString("Partidas_ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de puntajes.
        /// </summary>
        public static string Partidas_HistorialPuntajes {
            get {
                return ResourceManager.GetString("Partidas_HistorialPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta partida ya no está disponible. Por favor elige otra..
        /// </summary>
        public static string Partidas_NoDisponibleMensaje {
            get {
                return ResourceManager.GetString("Partidas_NoDisponibleMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida no disponible.
        /// </summary>
        public static string Partidas_NoDisponibleTitulo {
            get {
                return ResourceManager.GetString("Partidas_NoDisponibleTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu puntaje:.
        /// </summary>
        public static string Partidas_PuntajePrefijo {
            get {
                return ResourceManager.GetString("Partidas_PuntajePrefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay partidas disponibles en este momento..
        /// </summary>
        public static string Partidas_SinPartidas {
            get {
                return ResourceManager.GetString("Partidas_SinPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Únete a una partida o crea la tuya..
        /// </summary>
        public static string Partidas_Subtitulo {
            get {
                return ResourceManager.GetString("Partidas_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas en curso.
        /// </summary>
        public static string Partidas_Titulo {
            get {
                return ResourceManager.GetString("Partidas_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Partidas.
        /// </summary>
        public static string Partidas_TituloVentana {
            get {
                return ResourceManager.GetString("Partidas_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirme.
        /// </summary>
        public static string Partidas_Unirme {
            get {
                return ResourceManager.GetString("Partidas_Unirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil.
        /// </summary>
        public static string Partidas_VerPerfil {
            get {
                return ResourceManager.GetString("Partidas_VerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string Perfil_EditarPerfil {
            get {
                return ResourceManager.GetString("Perfil_EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTIDAS GANADAS.
        /// </summary>
        public static string Perfil_PartidasGanadas {
            get {
                return ResourceManager.GetString("Perfil_PartidasGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PENALIZACIONES.
        /// </summary>
        public static string Perfil_Penalizaciones {
            get {
                return ResourceManager.GetString("Perfil_Penalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PUNTAJE TOTAL.
        /// </summary>
        public static string Perfil_PuntajeTotal {
            get {
                return ResourceManager.GetString("Perfil_PuntajeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIVAL VENCIDO.
        /// </summary>
        public static string Perfil_RivalVencido {
            get {
                return ResourceManager.GetString("Perfil_RivalVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu información personal.
        /// </summary>
        public static string Perfil_Subtitulo {
            get {
                return ResourceManager.GetString("Perfil_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string Perfil_Titulo {
            get {
                return ResourceManager.GetString("Perfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorcado · Mi perfil.
        /// </summary>
        public static string Perfil_TituloVentana {
            get {
                return ResourceManager.GetString("Perfil_TituloVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string RegistrarCuenta_ConfirmarContrasena {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ConfirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un número de celular válido (10 a 15 dígitos)..
        /// </summary>
        public static string RegistrarCuenta_ErrorCelularInvalido {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCelularInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no cumple los requisitos..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenaRequisitos {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string RegistrarCuenta_ErrorContrasenasNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorContrasenasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo ya tiene una cuenta asociada..
        /// </summary>
        public static string RegistrarCuenta_ErrorCorreoExiste {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCorreoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un correo electrónico válido..
        /// </summary>
        public static string RegistrarCuenta_ErrorCorreoInvalido {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes tener al menos 10 años cumplidos para registrarte..
        /// </summary>
        public static string RegistrarCuenta_ErrorEdadMinima {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorEdadMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona tu fecha de nacimiento..
        /// </summary>
        public static string RegistrarCuenta_ErrorFechaVacia {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ErrorFechaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada con éxito! Ahora puedes iniciar sesión..
        /// </summary>
        public static string RegistrarCuenta_ExitoMensaje {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro exitoso.
        /// </summary>
        public static string RegistrarCuenta_ExitoTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string RegistrarCuenta_FechaNacimiento {
            get {
                return ResourceManager.GetString("RegistrarCuenta_FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string RegistrarCuenta_NombreCompleto {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de celular.
        /// </summary>
        public static string RegistrarCuenta_NumeroCelular {
            get {
                return ResourceManager.GetString("RegistrarCuenta_NumeroCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos 8 caracteres.
        /// </summary>
        public static string RegistrarCuenta_Req8 {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Req8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra mayúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMayuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra minúscula.
        /// </summary>
        public static string RegistrarCuenta_ReqMinuscula {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un número.
        /// </summary>
        public static string RegistrarCuenta_ReqNumero {
            get {
                return ResourceManager.GetString("RegistrarCuenta_ReqNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TU CONTRASEÑA DEBE TENER:.
        /// </summary>
        public static string RegistrarCuenta_RequisitosTitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_RequisitosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo unos datos y ya puedes empezar a jugar..
        /// </summary>
        public static string RegistrarCuenta_Subtitulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una cuenta.
        /// </summary>
        public static string RegistrarCuenta_Titulo {
            get {
                return ResourceManager.GetString("RegistrarCuenta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes cuenta?.
        /// </summary>
        public static string RegistrarCuenta_YaTienesCuenta {
            get {
                return ResourceManager.GetString("RegistrarCuenta_YaTienesCuenta", resourceCulture);
            }
        }
    }
}
