//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoWCF
{
    using System;
    using System.Collections.Generic;

    public partial class historial_puntaje
    {
        public int idPuntaje { get; set; }
        public string tipoPuntaje { get; set; }
        public int puntos { get; set; }
        public int idJugador { get; set; }
        public int idJugadorRival { get; set; }
        public int idPartida { get; set; }
        public int idPalabra { get; set; }

        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual partida partida { get; set; }
        public virtual palabra palabra { get; set; }
    }
}
