//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoWCF
{
    using System;
    using System.Collections.Generic;

    public partial class movimiento
    {
        public int idMovimiento { get; set; }
        public string letraIngresada { get; set; }
        public int idPartida { get; set; }
        public bool esCorrecta { get; set; }

        public virtual partida partida { get; set; }
    }
}
