//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class palabra_descripcion
    {
        public int idPalabra { get; set; }
        public string idioma { get; set; }
        public string descripcion { get; set; }
    
        public virtual palabra palabra { get; set; }
    }
}
