//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class partida
    {
        public int idPartida { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string estado { get; set; }
        public int idJugadorUno { get; set; }
        public Nullable<int> idJugadorDos { get; set; }
        public Nullable<int> idPalabra { get; set; }
    
        public virtual palabra palabra { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
